# Configuration for golangci-lint v2
version: "2"

run:
  timeout: 5m
  tests: true
  issues-exit-code: 1
  modules-download-mode: readonly
  concurrency: 4
  build-tags: []

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - goconst
    - gocyclo
    - misspell
    - unparam
    - prealloc
    - gosec
    - bodyclose
    - unconvert
    - dupl
    - gocritic
    - revive
  disable:
    - gochecknoinits
    - gochecknoglobals
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    gocyclo:
      min-complexity: 29
    gosec:
      excludes:
        - G104 # Handled by errcheck
    goconst:
      min-len: 3
      min-occurrences: 3
    misspell:
      locale: US
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    dupl:
      threshold: 150
