# Configuration for golangci-lint, using schema version "2".
# This structure is based on the official JSON schema for modern golangci-lint versions.
version: "2"

run:
  timeout: 5m
  tests: true
  issues-exit-code: 1
  modules-download-mode: readonly
  concurrency: 4
  build-tags: []

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - goconst
    - gocyclo
    - misspell
    - unparam
    - prealloc
    - gosec
    - bodyclose
    - unconvert
    - dupl
    - gocritic
    - revive
  disable:
    - gochecknoinits
    - gochecknoglobals
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    gocyclo:
      min-complexity: 29
    gosec:
      excludes:
        - G104 # Handled by errcheck
    goconst:
      min-len: 3
      min-occurrences: 3
    misspell:
      locale: US
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    dupl:
      threshold: 150
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gosec
      - path: cmd/examples/
        linters:
          - errcheck
      - path: internal/domain/
        text: "exported.*should have comment.*or be unexported"
        linters:
          - revive
      - path: pkg/
        text: "exported.*should have comment.*or be unexported"
        linters:
          - revive
      - text: "stutter"
        linters:
          - revive
      - linters:
          - gocritic
        text: "hugeParam"
      - text: "Id"
        linters:
          - revive

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    text:
      print-issued-lines: true
      print-linter-name: true
  sort-order:
    - linter
    - file
